name: firebase_compute
description: Library for doing reactive computations with firebase.
version: 0.1.2
author: Rik Bellens <rik.bellens@appsup.be>
homepage: https://github.com/appsup-dart/firebase_compute

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  firebase_dart: '>=0.7.2 <0.8.0'
  intl: '>=0.14.0 <0.15.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
